using UnityEngine;

public class ParallaxLoop : MonoBehaviour
{
    public Transform cameraTransform; // CamÃ©ra principale
    public float parallaxFactor = 0.5f; // Vitesse relative
    public float spriteWidth; // Largeur du sprite pour looping

    public Vector3 startPosition;

    // Start is called once before the first execution of Update after the MonoBehaviour is created
    void Start()
    {
        if (cameraTransform == null)
        {
            cameraTransform = Camera.main.transform;
        }

        startPosition = transform.position;
    }

    // Update is called once per frame
    void LateUpdate()
    {
        float deltaX = cameraTransform.position.x * parallaxFactor;
        transform.position = new Vector3(startPosition.x + deltaX, startPosition.y, startPosition.z);

        // Looping horizontal
        float offset = cameraTransform.position.x - startPosition.x;

        if (offset > spriteWidth)
        {
            startPosition.x += spriteWidth;
        }
        else if (offset < -spriteWidth)
        {
            startPosition.x -= spriteWidth;
        }
    }
}
